project:
  type: website

website:
  title: "che-Norma!"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  body-footer: "Creado y mantenido por Álvaro Cabana."
  search: 
    location: navbar
    type: overlay

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

